### ISSUE TITLE
ID 1055 problem_390 HTML problem doesn't work

### ISSUE THREAD

**Issue by marshall62** [perspegrity5/UMassONRMathTutorsContent#37]
THere are 4 answers A-D .   B should be the correct answer.   The db has E as the correct answer.  So
there is no answer that can be clicked on that is right.

I gotta say,  I'm very doubtful of the quality control going into HTML problems authoring, entry, and testing.   This problem is marked READY and it is new.   How can errors like this be showing up on new problems that should be thoroughly tested before marked ready?????

**Comment by lynn99** [comment]
My records show that this problem was disabled and sent back for correction.  
—
Lynn Stephens
Post Doctoral Researcher
School of Computer Science  and 
College of Education
University of Massachusetts—Amherst
(413) 230-4634

**Comment by lynn99** [comment]
This problem was recently repaired and re-uploaded.  My records show that its status had been Disabled and was then changed to Testable.  

During testing, the error in the DB was noted by Tom and flagged but apparently not repaired.

I do not show that the status was ever changed to Ready.

—
Lynn Stephens
Post Doctoral Researcher
School of Computer Science  and 
College of Education
University of Massachusetts—Amherst
(413) 230-4634

**Comment by perspegrity5** [comment]
this problem does not appear to be uploaded--not sure what devel folder it is in, (assuming  its been fixed)
