### ISSUE TITLE
problem id 543 has broken buttons but marked as ready

### ISSUE THREAD

**Issue by marshall62** [perspegrity5/UMassONRMathTutorsContent#43]
So there is definitely a bug in the CMS.  I found yet another problem (543) that is set to "ready"
but has broken buttons and was turned off at some time in the past.

I think you are going to need to run a full audit of every problem in the system that is marked ready
(using the dialog that allows problem selection) to validate that we do not have broken problems turned on.   This the fifth one I've found in about 6 weeks.

**Comment by lynn99** [comment]
There are also HTML problems marked as Ready but that have had issues identified.  I know this because we have the repaired versions waiting to be checked and then uploaded.

I think we need a separate auditing system for the Flash and for the HTML.  We have a procedure to check for 
Flash: broken buttons
HTML: outdated templates

but neither of these procedures are specified in the CMS.  

Doing the Flash procedure on an HTML problem will yield a false positive and vice versa.

—
Lynn Stephens
Post Doctoral Researcher
School of Computer Science  and 
College of Education
University of Massachusetts—Amherst
(413) 230-4634

**Comment by perspegrity5** [comment]
Dave, 

I tried this problem (_543) and it works fine for me (Safari / Mac).  You also had a problem with #546 problem_561 which worked fine for me. Also, you said that the problems pointed to by the new Lessons were broken problems but they seem to work fine. 

Also, I did a compare of what was in the database 6 months ago to now and there did not seem to be any unexpected changes in problem status. This is as close to a "full audit" as I could do.  If you have an earlier version of the database backup I should look at send a pointer or (better) email the problem table from that backup.

So as far as I can tell whenever you think there is an issue with the CMS (having to do with problem status) that has not been the case. Something else must be happening here, so lets take a closer look next time it comes up.  

--thanks, Tom

**Comment by jwnewman** [comment]
Dave and I fixed these problems. I don't think it's your CMS' fault. It's just a problem that was never committed to mscontent in its fixed form. Unfortunately I don't have a comprehensive list of which problems never made it in, so these might keep trickling in.

**Comment by perspegrity5** [comment]
This sounds good Lynn.

To be clear (I think we agree) the CMS does not specify a testing "procedure" it only gives places to record the results. So far testing procedures have come from you to DA and MT.  

On Oct 28, 2014, at 1:46 PM, lynn99 notifications@github.com wrote:

> There are also HTML problems marked as Ready but that have had issues identified. I know this because we have the repaired versions waiting to be checked and then uploaded. 

Could it be because they are "Minor Issues" which are left as ready?  If you sent examples I can;t find them--which problems?
I thought I had made all the needed changes from the ONR batch 6,8; but any results from the recent HTML5 tests for Affect (batch 11) have _not_ resulted in problem status changes yet. 

> I think we need a separate auditing system for the Flash and for the HTML. We have a procedure to check for 
> Flash: broken buttons 
> HTML: outdated templates 

Are they close enough that a branch in one procedure would be better?

> but neither of these procedures are specified in the CMS. 
> 
> Doing the Flash procedure on an HTML problem will yield a false positive and vice versa.

**Comment by lynn99** [comment]
These problems should be ready for upload later today.  They are either on the ONR list or can replace broken Flash problems that are on the ONR list:
_251
_297
_347
_367
_381
_388
_389
_400
_406
_407
_420
_421
_423
_427
_800

—
Lynn Stephens
Post Doctoral Researcher
School of Computer Science  and 
College of Education
University of Massachusetts—Amherst
(413) 230-4634

**Comment by lynn99** [comment]
Also the 15 Formality conversions have been repaired and will be ready for upload.

—
Lynn Stephens
Post Doctoral Researcher
School of Computer Science  and 
College of Education
University of Massachusetts—Amherst
(413) 230-4634

**Comment by lynn99** [comment]
You made the status changes.  And then we fixed the problems.

—
Lynn Stephens
Post Doctoral Researcher
School of Computer Science  and 
College of Education
University of Massachusetts—Amherst
(413) 230-4634

**Comment by lynn99** [comment]
There is no parallel for the outdated template procedure in the Flash problems.  I think it shouldn’t be done at all for them.  It is time consuming and would likely produce false positives.

For the broken buttons issue, you might be able to make a branch as long as it is clear that what indicates OK in one branch actually indicates BROKEN in the other.  In one of them, the Xs are supposed to disappear and in the other one, they are not supposed to disappear.  (I always forget which is which.  Would be good to have that clear in the tool.)

By now Minghui and Danielle may be clear on which is which, but if they don’t do testing for a couple months?

I suspect separate issues will continue to arise for these two types of problems as the system evolves.  Not sure what the answer is.

—
Lynn Stephens
Post Doctoral Researcher
School of Computer Science  and 
College of Education
University of Massachusetts—Amherst
(413) 230-4634
